name: Send Coverage Report to DeepSource
on: pull_request
jobs:
  report-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - run: npm install
      - run: npm run build
      - run: npm run coverage
      - run: curl https://deepsource.io/cli | sh
      - run: DEEPSOURCE_DSN=${{ secrets.DEEPSOURCE_DSN }} ./bin/deepsource report --analyzer test-coverage --key javascript --value-file coverage/lcov.info
